export const portfolioData = [
  // Group 1: 3000x2000 (3:2 Aspect Ratio)
  {
    id: "bg-removal",
    prefix: "Background",
    highlight: "Removal",
    aspect: "aspect-[3/2.5]",
    images: [
      "/portfolio/bg-removal/BG-Removal-1.jpg",
      "/portfolio/bg-removal/BG-Removal-2.jpg",
      "/portfolio/bg-removal/BG-Removal-3.jpg",
      "/portfolio/bg-removal/BG-Removal-4.jpg",
    ],
  },
  {
    id: "shadow-creation",
    prefix: "Shadow",
    highlight: "Creation",
    aspect: "aspect-[3/2.5]",
    images: [
      "/portfolio/shadow/High-end retouching service for ecommerce brands, catalogs, and advertising (1).jpg",
      "/portfolio/shadow/High-end retouching service for ecommerce brands, catalogs, and advertising (2).jpg",
      "/portfolio/shadow/High-end retouching service for ecommerce brands, catalogs, and advertising (3).jpg",
      "/portfolio/shadow/High-end retouching service for ecommerce brands, catalogs, and advertising (4).jpg",
    ],
  },
  {
    id: "image-masking",
    prefix: "Image",
    highlight: "Masking",
    aspect: "aspect-[3/2.5]",
    images: [
      "/portfolio/masking/professional-image-masking-fotoperfectionlab (1).jpg",
      "/portfolio/masking/professional-image-masking-fotoperfectionlab (2).jpg",
      "/portfolio/masking/professional-image-masking-fotoperfectionlab (3).jpg",
      "/portfolio/masking/professional-image-masking-fotoperfectionlab (4).jpg",
    ],
  },
  {
    id: "photo-retouching",
    prefix: "Photo",
    highlight: "Retouching",
    aspect: "aspect-[3/2.5]",
    images: [
      "/portfolio/photo-retouching/professional-image-editing-retouching-service-fotoperfectionlab (1).jpg",
      "/portfolio/photo-retouching/professional-image-editing-retouching-service-fotoperfectionlab (2).jpg",
      "/portfolio/photo-retouching/professional-image-editing-retouching-service-fotoperfectionlab (3).jpg",
      "/portfolio/photo-retouching/professional-image-editing-retouching-service-fotoperfectionlab (4).jpg",
      "/portfolio/photo-retouching/professional-image-editing-retouching-service-fotoperfectionlab (5).jpg",
      "/portfolio/photo-retouching/professional-image-editing-retouching-service-fotoperfectionlab (6).jpg",
      "/portfolio/photo-retouching/professional-image-editing-retouching-service-fotoperfectionlab (7).jpg",
      "/portfolio/photo-retouching/professional-image-editing-retouching-service-fotoperfectionlab (8).jpg",
    ],
  },
  {
    id: "jewellery-retouching",
    prefix: "Jewelery",
    highlight: "Retouching",
    aspect: "aspect-[3/2.5]",
    images: [
      "/portfolio/jewellery-retouching/E-commerce Jewelry Photo Editing (1).jpg",
      "/portfolio/jewellery-retouching/E-commerce Jewelry Photo Editing (2).jpg",
      "/portfolio/jewellery-retouching/E-commerce Jewelry Photo Editing (3).jpg",
      "/portfolio/jewellery-retouching/E-commerce Jewelry Photo Editing (4).jpg",
    ],
  },
  {
    id: "ghost-mannequin",
    prefix: "Ghost",
    highlight: "Mannequin",
    aspect: "aspect-[3/2.5]",
    images: [
      "/portfolio/ghost/Professional-Ghost-Mannequin-Editing-(1).jpg",
      "/portfolio/ghost/Professional-Ghost-Mannequin-Editing-(2).jpg",
      "/portfolio/ghost/Professional-Ghost-Mannequin-Editing-(4).jpg",
      "/portfolio/ghost/Professional-Ghost-Mannequin-Editing-(5).jpg",
    ],
  },
  {
    id: "ecommerce-editing",
    prefix: "E-commerce Photo",
    highlight: "Editing",
    aspect: "aspect-[3/2.5]",
    images: [
      "/portfolio/ecommerce-photo-editing/professional-image-editing-retouching-service-fotoperfectionlab (2).jpg",
      "/portfolio/ecommerce-photo-editing/professional-image-editing-retouching-service-fotoperfectionlab (3).jpg",
      "/portfolio/ecommerce-photo-editing/professional-image-editing-retouching-service-fotoperfectionlab (4).jpg",
      "/portfolio/ecommerce-photo-editing/professional-image-editing-retouching-service-fotoperfectionlab (5).jpg",
      "/portfolio/ecommerce-photo-editing/professional-image-editing-retouching-service-fotoperfectionlab (6).jpg",
      "/portfolio/ecommerce-photo-editing/professional-image-editing-retouching-service-fotoperfectionlab (7).jpg",
      "/portfolio/ecommerce-photo-editing/professional-image-editing-retouching-service-fotoperfectionlab (8).jpg",
      "/portfolio/ecommerce-photo-editing/professional-image-editing-retouching-service-fotoperfectionlab (9).jpg",
    ],
  },
  {
    id: "real-estate",
    prefix: "Real Estate Photo",
    highlight: "Editing",
    aspect: "aspect-[3/2.5]",
    images: [
      "/portfolio/realstate-photo-editing/Real-Estate-Photo-Editing-Service-(1).jpg",
      "/portfolio/realstate-photo-editing/Real-Estate-Photo-Editing-Service-(2).jpg",
      "/portfolio/realstate-photo-editing/Real-Estate-Photo-Editing-Service-(3).jpg",
      "/portfolio/realstate-photo-editing/Real-Estate-Photo-Editing-Service-(4).jpg",
      "/portfolio/realstate-photo-editing/Real-Estate-Photo-Editing-Service-(5).jpg",
      "/portfolio/realstate-photo-editing/Real-Estate-Photo-Editing-Service-(6).jpg",
      "/portfolio/realstate-photo-editing/Real-Estate-Photo-Editing-Service-(7).jpg",
      "/portfolio/realstate-photo-editing/Real-Estate-Photo-Editing-Service-(8).jpg",
    ],
  },
  {
    id: "food-retouching",
    prefix: "Food",
    highlight: "Retouching",
    aspect: "aspect-[3/2.5]",
    images: [
      "/portfolio/food-retouching/Food Product Retouching Service (1).jpg",
      "/portfolio/food-retouching/Food Product Retouching Service (2).jpg",
      "/portfolio/food-retouching/Food Product Retouching Service (3).jpg",
      "/portfolio/food-retouching/Food Product Retouching Service (4).jpg",
    ],
  },
  {
    id: "baby-photo",
    prefix: "Baby Photo",
    highlight: "Retouching",
    aspect: "aspect-[3/2.5]",
    images: [
      "/portfolio/baby-retouching/Baby Photo Retouching Service, Newborn Photo Editing (1).jpg",
      "/portfolio/baby-retouching/Baby Photo Retouching Service, Newborn Photo Editing (2).jpg",
      "/portfolio/baby-retouching/Baby Photo Retouching Service, Newborn Photo Editing (3).jpg",
      "/portfolio/baby-retouching/Baby Photo Retouching Service, Newborn Photo Editing (4).jpg",
    ],
  },
  {
    id: "beauty-retouching",
    prefix: "Beauty",
    highlight: "Retouching",
    aspect: "aspect-[2/2.5]",
    images: [
      "/portfolio/beauty-retouching/Beuty-Retouch-1.jpg",
      "/portfolio/beauty-retouching/Beuty-Retouch-2.jpg",
      "/portfolio/beauty-retouching/Beuty-Retouch-3.jpg",
      "/portfolio/beauty-retouching/Beuty-Retouch-4.jpg",
    ],
  },
  {
    id: "headshot-portrait",
    prefix: "Headshot & Portrait",
    highlight: "Retouching",
    aspect: "aspect-[2/3]",
    images: [
      "/portfolio/headshot-retouching/Corporate Headshot Editing Portrait Retouching (1).jpg",
      "/portfolio/headshot-retouching/Corporate Headshot Editing Portrait Retouching (2).jpg",
      "/portfolio/headshot-retouching/Corporate Headshot Editing Portrait Retouching (3).jpg",
      "/portfolio/headshot-retouching/Corporate Headshot Editing Portrait Retouching (4).jpg",
    ],
  },
  {
    id: "model-retouching",
    prefix: "Model",
    highlight: "Retouching",
    aspect: "aspect-[2/3]",
    images: [
      "/portfolio/model-retouching/Professional Model Photo Editing & Retouching (1).jpg",
      "/portfolio/model-retouching/Professional Model Photo Editing & Retouching (2).jpg",
      "/portfolio/model-retouching/Professional Model Photo Editing & Retouching (3).jpg",
      "/portfolio/model-retouching/Professional-Model-Photo-Editing-&-Retouching-(4).jpg",
    ],
  },
];
