export const servicesData = [
  {
    id: 1,
    title: "Clipping Path",
    description:
      "Clipping path service allows removing the unwanted objects background from photos. You can also do color separation using clipping path. We provide a manual clipping path service using adobe photoshop. Pricing may vary depending on image complexity but is very competitive.",
    features: [
      "Hand-made clipping path vectors",
      "Pricing depends on image complexity",
      "Up to 50% discount on bulk order",
      "Fast delivery within 24 hours",
      "24/7 customer support",
    ],
    beforeImage: "/services/clipping-path/CP-Before.jpg",
    afterImage: "/services/clipping-path/CP-After.jpg",
    link: "/services/clipping-path",
    showHome: false,
  },
  {
    id: 2,
    title: "Background Removal",
    description:
      "Instantly upgrade your product presentation by replacing distracting backgrounds with pure white or transparent backdrops, perfectly optimized for Amazon, Shopify, and eBay.",
    features: [
      "Pure white or transparent BG",
      "Amazon & Shopify compliant",
      "Smooth edge refinement",
      "Fast delivery within 24 hours",
      "24/7 customer support",
    ],
    beforeImage: "/services/bg-removal/BG-Removal-Before.jpg",
    afterImage: "/services/bg-removal/BG-Removal-After.jpg",
    link: "/services/background-removal",
    showHome: false,
  },
  {
    id: 3,
    title: "Shadow Creation",
    description:
      "Add depth and realism to flat product images with custom drop shadows, natural shadows, or reflections. Creates a 3D effect that increases perceived product value.",
    features: [
      "Drop, natural, & reflection shadows",
      "Realistic 3D depth addition",
      "Consistent lighting angles",
      "Fast delivery within 24 hours",
      "24/7 customer support",
    ],
    beforeImage: "/services/shadow-creation/Shadow-Before.jpg",
    afterImage: "/services/shadow-creation/Shadow-After.jpg",
    link: "/services/shadow-creation",
    showHome: false,
  },
  {
    id: 4,
    title: "Image Masking",
    description:
      "Advanced image masking for complex subjects like hair, fur, or translucent objects where standard clipping paths fall short. Ensures natural, soft edges on any background.",
    features: [
      "Alpha channel masking",
      "Hair and fur detailing",
      "Translucent object masking",
      "Fast delivery within 24 hours",
      "24/7 customer support",
    ],
    beforeImage: "/services/image-masking/Masking-Before.jpg",
    afterImage: "/services/image-masking/Masking-After.jpg",
    link: "/services/image-masking",
    showHome: false,
  },
  {
    id: 5,
    title: "Photo Retouching",
    description:
      "High-end retouching to clean up dust, scratches, glares, and imperfections. Enhances the overall aesthetic while maintaining natural textures and materials.",
    features: [
      "Dust and scratch removal",
      "Texture preservation",
      "Highlight and glare adjustment",
      "Fast delivery within 24 hours",
      "24/7 customer support",
    ],
    beforeImage: "/services/photo-retouching/Photo-Retouching-Before.jpg",
    afterImage: "/services/photo-retouching/Photo-Retouching-After.jpg",
    link: "/services/photo-retouching",
    showHome: false,
  },
  {
    id: 6,
    title: "Jewelry Retouching",
    description:
      "Specialized retouching for fine jewelry. We enhance gem sparkle, correct metal colors, remove macro-lens dust, and add distinct shines to make pieces look luxurious.",
    features: [
      "Diamond and gem enhancement",
      "Metal color correction",
      "Focus stacking adjustments",
      "Fast delivery within 24 hours",
      "24/7 customer support",
    ],
    beforeImage: "/services/jewellery-retouching/Jewellery-Before.jpg",
    afterImage: "/services/jewellery-retouching/Jewellery-After.jpg",
    link: "/services/jewellery-retouching",
    showHome: true,
  },
  {
    id: 7,
    title: "Ghost Mannequin",
    description:
      "Remove mannequins and combine front and inner neck shots to create a 3D hollow 'ghost' effect for apparel. The industry standard for fashion e-commerce.",
    features: [
      "Neck joint and inner shadow",
      "Sleeve and hem adjustments",
      "Wrinkle removal included",
      "Fast delivery within 24 hours",
      "24/7 customer support",
    ],
    beforeImage: "/services/ghost-mannequin/Ghost-Before.jpg",
    afterImage: "/services/ghost-mannequin/Ghost-After.jpg",
    link: "/services/ghost-mannequin",
    showHome: false,
  },
  {
    id: 8,
    title: "Apparel Editing",
    description:
      "Comprehensive editing for clothing items including wrinkle removal, shape symmetry correction, and color matching to present garments flawlessly.",
    features: [
      "Symmetry and shape correction",
      "Fabric smoothing and wrinkle removal",
      "Color matching to physical items",
      "Fast delivery within 24 hours",
      "24/7 customer support",
    ],
    beforeImage: "/services/apparel-editing/Model-Retouching-Before.jpg",
    afterImage: "/services/apparel-editing/Model-Retouching-After.jpg",
    link: "/services/apparel-editing",
    showHome: false,
  },
  {
    id: 9,
    title: "E-commerce Photo Editing",
    description:
      "A complete package tailored for online retailers. Includes background removal, resizing, margin alignment, and basic retouching for platform compliance.",
    features: [
      "Platform-specific resizing",
      "Consistent margin alignment",
      "Batch processing workflow",
      "Fast delivery within 24 hours",
      "24/7 customer support",
    ],
    beforeImage: "/services/ecommerce-photo-editing/professional-image-editing-retouching-service-fotoperfectionlab-Before.jpg",
    afterImage: "/services/ecommerce-photo-editing/professional-image-editing-retouching-service-fotoperfectionlab-After.jpg",
    link: "/services/ecommerce-photo-editing",
    showHome: true,
  },
  {
    id: 10,
    title: "Color Correction",
    description:
      "Ensure exact color representation across your entire product catalog. We adjust white balance, exposure, and hue to match your physical products perfectly.",
    features: [
      "Accurate color matching",
      "White balance adjustments",
      "Exposure correction",
      "Fast delivery within 24 hours",
      "24/7 customer support",
    ],
    beforeImage: "/services/color-correction/Color-Correction-Before.jpg",
    afterImage: "/services/color-correction/Color-Correction-After.jpg",
    link: "/services/color-correction",
    showHome: false,
  },
  {
    id: 11,
    title: "Real Estate Photo Editing",
    description:
      "Transform property photos with HDR blending, sky replacements, window masking, and perspective corrections to attract more buyers and renters.",
    features: [
      "HDR blending and sky replacement",
      "Perspective and lens correction",
      "Lawn enhancement",
      "Fast delivery within 24 hours",
      "24/7 customer support",
    ],
    beforeImage: "/services/real-estate-photo-editing/Real-Estate-Before.jpg",
    afterImage: "/services/real-estate-photo-editing/Real-Estate-After.jpg",
    link: "/services/real-estate-photo-editing",
    showHome: false,
  },
  {
    id: 12,
    title: "Food Retouching",
    description:
      "Make culinary dishes look mouth-watering. We adjust lighting, enhance colors, remove stray crumbs, and emphasize textures for menus and marketing.",
    features: [
      "Color vibrancy enhancement",
      "Lighting and steam adjustments",
      "Distraction removal",
      "Fast delivery within 24 hours",
      "24/7 customer support",
    ],
    beforeImage: "/services/food-retouching/Food-Retouch-Before.jpg",
    afterImage: "/services/food-retouching/Food-Retouch-After.jpg",
    link: "/services/food-retouching",
    showHome: false,
  },
  {
    id: 13,
    title: "Headshot & Portrait Retouching",
    description:
      "Professional retouching for corporate headshots and personal portraits. We balance skin tones, remove blemishes, and brighten eyes while keeping it natural.",
    features: [
      "Natural skin smoothing",
      "Teeth whitening & eye brightening",
      "Stray hair removal",
      "Fast delivery within 24 hours",
      "24/7 customer support",
    ],
    beforeImage: "/services/headshot-retouching/Headshot-Retouch-Before.jpg",
    afterImage: "/services/headshot-retouching/Headshot-Retouch-After.jpg",
    link: "/services/headshot-portrait-retouching",
    showHome: true,
  },
  {
    id: 14,
    title: "Baby Photo Retouching",
    description:
      "Gentle retouching for newborn and baby photography. We smooth out flaky skin, correct redness, and create a soft, dreamy aesthetic for cherished memories.",
    features: [
      "Redness and blemish correction",
      "Soft skin smoothing",
      "Background cleanup",
      "Fast delivery within 24 hours",
      "24/7 customer support",
    ],
    beforeImage: "/services/baby-retouching/Baby-Photo-Retouching-Before.jpg",
    afterImage: "/services/baby-retouching/Baby-Photo-Retouching-After.jpg",
    link: "/services/baby-photo-retouching",
    showHome: false,
  },
  {
    id: 15,
    title: "Beauty Retouching",
    description:
      "High-end beauty retouching for magazines and cosmetics. Utilizing frequency separation and dodge/burn to preserve skin texture while achieving flawless results.",
    features: [
      "Frequency separation technique",
      "Dodge and burn contouring",
      "Makeup enhancement",
      "Fast delivery within 24 hours",
      "24/7 customer support",
    ],
    beforeImage: "/services/beauty-retouching/Beuty-Retouch-Before.jpg",
    afterImage: "/services/beauty-retouching/Beuty-Retouch-After.jpg",
    link: "/services/beauty-retouching",
    showHome: true,
  },
  {
    id: 16,
    title: "Model Retouching",
    description:
      "Comprehensive model retouching for fashion campaigns. Includes body contouring, clothing adjustments, skin perfecting, and atmospheric color grading.",
    features: [
      "Body and posture contouring",
      "Skin and clothing perfection",
      "Atmospheric color grading",
      "Fast delivery within 24 hours",
      "24/7 customer support",
    ],
    beforeImage: "/services/model-retouching/Model-photo-retouching-Before.jpg",
    afterImage: "/services/model-retouching/Model-photo-retouching-After.jpg",
    link: "/services/model-retouching",
    showHome: false,
  },
  {
    id: 17,
    title: "AI Photo Editing",
    description:
      "Leverage advanced AI tools combined with human expertise for rapid upscaling, generation of realistic elements, and complex scene modifications.",
    features: [
      "AI-assisted upscaling",
      "Generative fill and expansion",
      "Prompt-based element addition",
      "Fast delivery within 24 hours",
      "24/7 customer support",
    ],
    beforeImage: "/services/ai-photo-editing/AI-Photo-Edit-Before.jpg",
    afterImage: "/services/ai-photo-editing/AI-Photo-Edit-After.jpg",
    link: "/services/ai-photo-editing",
    showHome: false,
  },
  {
    id: 18,
    title: "Photo Restoration",
    description:
      "Breathe new life into old, torn, or faded photographs. We repair physical damage, restore lost contrast, and bring back details from historic images.",
    features: [
      "Tear and scratch repair",
      "Fading and contrast recovery",
      "Detail sharpening",
      "Fast delivery within 24 hours",
      "24/7 customer support",
    ],
    beforeImage: "/services/photo-restoration/Restoration-Before.jpg",
    afterImage: "/services/photo-restoration/Restoration-After.jpg",
    link: "/services/photo-restoration",
    showHome: false,
  },
  {
    id: 19,
    title: "Photo Manipulation",
    description:
      "Creative photo manipulation to combine multiple images into a seamless, surreal, or hyper-realistic composition. Perfect for advertising and concept art.",
    features: [
      "Seamless image compositing",
      "Lighting and shadow matching",
      "Creative concept execution",
      "Fast delivery within 24 hours",
      "24/7 customer support",
    ],
    beforeImage: "/services/photo-manipulation/Photo-Manipulation-Before.jpg",
    afterImage: "/services/photo-manipulation/Photo-Manipulation-After.jpg",
    link: "/services/photo-manipulation",
    showHome: false,
  },
  {
    id: 20,
    title: "Photo Colorization",
    description:
      "Accurately add historically appropriate and vibrant colors to black and white photography, revitalizing the past with stunning realism.",
    features: [
      "Accurate historical coloring",
      "Vibrant skin tone matching",
      "Texture-aware tinting",
      "Fast delivery within 24 hours",
      "24/7 customer support",
    ],
    beforeImage: "/services/photo-colorization/Photo-Colorization-Before.jpg",
    afterImage: "/services/photo-colorization/Photo-Colorization-After.jpg",
    link: "/services/photo-colorization",
    showHome: false,
  },
];